const BASE_FEE = {
  ETH_TOCKABLE: 0.00015,
  ETH_REGULAR: 0.000075,
  POLYGON_TOCKABLE: 0.6,
  POLYGON_REGULAR: 0.3,
};

export const chainData = [
  {
    chainId: 1,
    url: "https://etherscan.io",
    name: "Ethereum",
    scan: "Etherscan.io",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 10,
    url: "https://optimistic.etherscan.io",
    name: "Optimism",
    scan: "Optimistic.etherscan.io",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 11155420,
    url: "https://optimism-sepolia.blockscout.com",
    name: "Optimism Sepolia'",
    scan: "Optimism-sepolia.blockscout.com",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 137,
    url: "https://polygonscan.com",
    name: "Polygon",
    scan: "Polygonscan.com",
    nativeToken: "MATIC",
    base_fee: BASE_FEE.POLYGON_TOCKABLE,
    regular_base_fee: BASE_FEE.POLYGON_REGULAR,
  },
  {
    chainId: 80001,
    url: "https://mumbai.polygonscan.com",
    name: "Polygon mumbai",
    scan: "Mumbai.polygonscan.com",
    nativeToken: "MATIC",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 8453,
    url: "https://basescan.org",
    name: "Base",
    scan: "Basescan.org",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 84532,
    url: "https://base-sepolia.blockscout.com",
    name: "Base Sepolia",
    scan: "Base-sepolia.blockscout.com",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 59144,
    url: "https://lineascan.build",
    name: "Linea Mainnet",
    scan: "Lineascan.build",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 168587773,
    url: "https://testnet.blastscan.io",
    name: "Blast Sepolia",
    scan: "Testnet.blastscan.io",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 59140,
    url: "https://goerli.lineascan.build",
    name: "Linea Goerli",
    scan: "Goerli.lineascan.build",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
  {
    chainId: 81457,
    url: "https://blastscan.io",
    name: "Blast",
    scan: "Blastscan.io",
    nativeToken: "ETH",
    base_fee: BASE_FEE.ETH_TOCKABLE,
    regular_base_fee: BASE_FEE.ETH_REGULAR,
  },
];
