import {
  linea,
  baseGoerli,
  mainnet,
  polygon,
  optimism,
  optimismGoerli,
  base,
  polygonMumbai,
} from "wagmi/chains";

export const chainData = [
  {
    chainId: mainnet.id,
    url: mainnet.blockExplorers.default.url,
    name: mainnet.name,
    scan: "Etherscan.io",
    nativeToken: mainnet.nativeCurrency.symbol,
    base_fee: 0.0002,
  },
  {
    chainId: optimism.id,
    url: "https://optimistic.etherscan.io",
    name: "Optimism",
    scan: "Optimistic.etherscan.io",
    nativeToken: optimism.nativeCurrency.symbol,
    base_fee: 0.0002,
  },
  {
    chainId: optimismGoerli.id,
    url: optimismGoerli.blockExplorers.default.url,
    name: "Optimism goerli",
    scan: "Goerli-optimistic.etherscan.io",
    nativeToken: optimismGoerli.nativeCurrency.symbol,
    base_fee: 0.0002,
  },
  {
    chainId: polygon.id,
    url: polygon.blockExplorers.default.url,
    name: polygon.name,
    scan: "Polygonscan.com",
    nativeToken: polygon.nativeCurrency.symbol,
    base_fee: 0.5,
  },
  {
    chainId: polygonMumbai.id,
    url: polygonMumbai.blockExplorers.default.url,
    name: "Polygon mumbai",
    scan: "Mumbai.polygonscan.com",
    nativeToken: polygonMumbai.nativeCurrency.symbol,
    base_fee: 0.0002,
  },
  {
    chainId: base.id,
    url: base.blockExplorers.default.url,
    name: base.name,
    scan: "Basescan.org",
    nativeToken: base.nativeCurrency.symbol,
    base_fee: 0.0002,
  },
  {
    chainId: baseGoerli.id,
    url: baseGoerli.blockExplorers.default.url,
    name: baseGoerli.name,
    scan: "Goerli.basescan.org",
    nativeToken: baseGoerli.nativeCurrency.symbol,
    base_fee: 0.0002,
  },
  {
    chainId: linea.id,
    url: linea.blockExplorers.default.url,
    name: linea.name,
    scan: "Lineascan.build",
    nativeToken: linea.nativeCurrency.symbol,
    base_fee: 0.0002,
  },
];
